POST http://localhost:5000/generate/data-processor HTTP/1.1
Content-Type: application/json

{
  "idTeacher": 1,
  "idYear": 1,
  "idDepartment": 1,
  "firstSemester": {
    "data": [
      {
        "idDiscipline": 1,
        "idGroups": [
          1
        ]
      },
      {
        "idDiscipline": 2,
        "idGroups": [
          1,2
        ]
      }
    ]
  },
  "secondSemester": {
    "data": [
      {
        "idDiscipline": 2,
        "idGroups": [
          1
        ]
      }, {
        "idDiscipline": 1,
        "idGroups": [
          2
        ]
      }
    ]
  }
}