#POST http://localhost:5000/ranks/create HTTP/1.1
#Content-Type: application/json
#
#{
#  "value": "Солдат"
#}

#GET http://localhost:5000/ranks/all HTTP/1.1

#POST http://localhost:5000/ranks/create-many HTTP/1.1
#Content-Type: application/json
#
#{
#  "list": [
#    {
#      "value": "Старший солдат"
#    },
#    {
#      "value": "Молодший сержант"
#    },
#    {
#      "value": "Сержант"
#    },
#    {
#      "value": "Старший сержант"
#    },
#    {
#      "value": "Головний сержант"
#    },
#    {
#      "value": "Майстер-сержант"
#    },
#    {
#      "value": "Головний майстер-сержант"
#    },
#    {
#      "value": "Молодший лейтенант"
#    },
#    {
#      "value": "Лейтенант"
#    },
#    {
#      "value": "Старший лейтенант"
#    },
#    {
#      "value": "Капітан"
#    },
#    {
#      "value": "Майор"
#    },
#    {
#      "value": "Підполковник"
#    },
#    {
#      "value": "Полковник"
#    },
#    {
#      "value": "Бригадний генерал"
#    },
#    {
#      "value": "Генерал-майор"
#    },
#    {
#      "value": "Генерал-лейтенант"
#    },
#    {
#      "value": "Генерал-полковник"
#    },
#    {
#      "value": "Генерал армії України"
#    }
#  ]
#}
#
