POST http://localhost:5000/discipline/create HTTP/1.1
Content-Type: application/json

{
  "codeEducationalComponent": "ЗО.03",
  "nameEducationalComponent": "Web-технології та Web-дизайн",
  "idDepartment": 1,
  "creditsECTS": 3.5,
  "totalHours": 135,
  "semesterHours": 135,
  "semesterClassroomHours": 86,
  "semesterLecturesHours": 8,
  "semesterGroupSeminarHours": 32,
  "semesterPractiseHours": 46,
  "semesterIndependentHors": 49,
  "semesterCourseWorkCount": 1,
  "semesterModuleWorkCount": 1,
  "semesterRGRWorkCount": 0,
  "semesterAbstractCount": 0,
  "isSemesterExamControl": true,
  "isSemesterTestControl": false,
  "semesterCount": 7
}