const input = {
  teacher: "",
  department: "",
  year: "",
  group: ""
};

// Перша сторінка
const data = {
  "departmentFullName": "Кафедра комп’ютерних інформаційних технологій",
  "departmentCode": 22,
  "departmentCommanderRank": "полковник",
  "departmentCommanderFirstName": "Е",
  "departmentCommanderSecondName": "БОВДА",
  "nowYear": "2023",
  "fromTheYear": "2023",
  "upToYear": "2024",
  "teacherPosition": "доцента кафедри",
  "positionRate": "ставка",
  "teacherDegree": "кандидата технічних наук",
  "teacherRank": "підполковника",
  "teacherSecondName": "ЗДОРЕНКА",
  "teacherFirstName": "Юрія",
  "teacherThirdName": "Миколайовича",
  "firstSemester": 1,
  "disciplines": [
  {
    "name": "Операційні системи  (ЗФН)",
    "codeSpecialize": "КН",
    "courseStudy": 2,
    "countOfGroup": 21,
    "groupCode": 29101,
    "totalLectures": 6,
    "totalGroup": 30,
    "totalPractice": 40,
    "verificationLaboratoryWork": 0,
    "conductingTacticalTraining": 0
  },
  {
    "name": "Операційні системи  (ЗФН)",
    "codeSpecialize": "КН",
    "courseStudy": 2,
    "countOfGroup": 21,
    "groupCode": 29201,
    "totalLectures": 6,
    "totalGroup": 30,
    "totalPractice": 40,
    "verificationLaboratoryWork": 0,
    "conductingTacticalTraining": 0
  },
  {
    "name": "Операційні системи  (ЗФН)",
    "codeSpecialize": "КН",
    "courseStudy": 2,
    "countOfGroup": 21,
    "groupCode": 29201,
    "totalLectures": 6,
    "totalGroup": 30,
    "totalPractice": 40,
    "verificationLaboratoryWork": 0,
    "conductingTacticalTraining": 0
  }
],
  "semesterLectures": 30,
  "semesterGroup": 60,
  "semesterPractice": 70,
  "semesterVerificationLaboratoryWork": 0,
  "semesterConductingTacticalTraining": 0,
  "disciplinesLoad": [
  {
    "holdingСonsultations": 0.09,
    "guidelinesDefenseTermPapers": 0,
    "checkingControl": 12.5,
    "conductingExam": 42.5,
    "managementMilitaryInternships": 50,
    "guidanceConsultationReview": 0,
    "defenseCertificationWorks": 0,
    "conductingComprehensiveExaminations": 0,
    "conductingOtherWorks": 0,
    "total": 94.6
  },
  {
    "holdingСonsultations": 0.09,
    "guidelinesDefenseTermPapers": 0,
    "checkingControl": 12.5,
    "conductingExam": 42.5,
    "managementMilitaryInternships": 50,
    "guidanceConsultationReview": 0,
    "defenseCertificationWorks": 0,
    "conductingComprehensiveExaminations": 0,
    "conductingOtherWorks": 0,
    "total": 94.6
  },
  {
    "holdingСonsultations": 0.09,
    "guidelinesDefenseTermPapers": 0,
    "checkingControl": 12.5,
    "conductingExam": 42.5,
    "managementMilitaryInternships": 50,
    "guidanceConsultationReview": 0,
    "defenseCertificationWorks": 0,
    "conductingComprehensiveExaminations": 0,
    "conductingOtherWorks": 0,
    "total": 94.6
  }
],
  "semesterHoldingСonsultations": 3,
  "semesterGuidelinesDefenseTermPapers": 0,
  "semesterCheckingControl": 12.5,
  "semesterConductingExam": 42.5,
  "semesterManagementMilitaryInternships": 50,
  "semesterGuidanceConsultationReview": 0,
  "semesterDefenseCertificationWorks": 0,
  "semesterConductingComprehensiveExaminations": 0,
  "semesterConductingOtherWorks": 0,
  "semesterTotal": 94.6,
  "secondSemester": 2,
  "fromTheNextYear": "2024",
  "upToNextYear": "2025",
  "disciplinesNextSemester": [
  {
    "name": "Операційні системи  (ЗФН)",
    "codeSpecialize": "КН",
    "courseStudy": 2,
    "countOfGroup": 21,
    "groupCode": 29201,
    "totalLectures": 6,
    "totalGroup": 30,
    "totalPractice": 40,
    "verificationLaboratoryWork": 0,
    "conductingTacticalTraining": 0
  },
  {
    "name": "Операційні системи  (ЗФН)",
    "codeSpecialize": "КН",
    "courseStudy": 2,
    "countOfGroup": 21,
    "groupCode": 29201,
    "totalLectures": 6,
    "totalGroup": 30,
    "totalPractice": 40,
    "verificationLaboratoryWork": 0,
    "conductingTacticalTraining": 0
  },
  {
    "name": "Операційні системи  (ЗФН)",
    "codeSpecialize": "КН",
    "courseStudy": 2,
    "countOfGroup": 21,
    "groupCode": 29201,
    "totalLectures": 6,
    "totalGroup": 30,
    "totalPractice": 40,
    "verificationLaboratoryWork": 0,
    "conductingTacticalTraining": 0
  }
],
  "nextSemesterLectures": 30,
  "nextSemesterGroup": 60,
  "nextSemesterPractice": 70,
  "nextSemesterVerificationLaboratoryWork": 0,
  "nextSemesterConductingTacticalTraining": 0,
  "yearLectures": 190,
  "yearGroup": 260,
  "yearPractice": 170,
  "yearVerificationLaboratoryWork": 0,
  "yearConductingTacticalTraining": 0,
  "disciplinesNextSemesterLoad": [
  {
    "holdingСonsultations": 0.09,
    "guidelinesDefenseTermPapers": 0,
    "checkingControl": 12.5,
    "conductingExam": 42.5,
    "managementMilitaryInternships": 50,
    "guidanceConsultationReview": 0,
    "defenseCertificationWorks": 0,
    "conductingComprehensiveExaminations": 0,
    "conductingOtherWorks": 0,
    "total": 94.6
  },{
    "holdingСonsultations": 0.09,
    "guidelinesDefenseTermPapers": 0,
    "checkingControl": 12.5,
    "conductingExam": 42.5,
    "managementMilitaryInternships": 50,
    "guidanceConsultationReview": 0,
    "defenseCertificationWorks": 0,
    "conductingComprehensiveExaminations": 0,
    "conductingOtherWorks": 0,
    "total": 94.6
  },{
    "holdingСonsultations": 0.09,
    "guidelinesDefenseTermPapers": 0,
    "checkingControl": 12.5,
    "conductingExam": 42.5,
    "managementMilitaryInternships": 50,
    "guidanceConsultationReview": 0,
    "defenseCertificationWorks": 0,
    "conductingComprehensiveExaminations": 0,
    "conductingOtherWorks": 0,
    "total": 94.6
  }
],
  "nextSemesterHoldingСonsultations": 3,
  "nextSemesterGuidelinesDefenseTermPapers": 0,
  "nextSemesterCheckingControl": 12.5,
  "nextSemesterConductingExam": 42.5,
  "nextSemesterManagementMilitaryInternships": 50,
  "nextSemesterGuidanceConsultationReview": 0,
  "nextSemesterDefenseCertificationWorks": 0,
  "nextSemesterConductingComprehensiveExaminations": 0,
  "nextSemesterConductingOtherWorks": 0,
  "nextSemesterTotal": 94.6,
  "yearHoldingСonsultations": 3,
  "yearGuidelinesDefenseTermPapers": 0,
  "yearCheckingControl": 12.5,
  "yearConductingExam": 42.5,
  "yearManagementMilitaryInternships": 50,
  "yearGuidanceConsultationReview": 0,
  "yearDefenseCertificationWorks": 0,
  "yearConductingComprehensiveExaminations": 0,
  "yearConductingOtherWorks": 0,
  "yearTotal": 94.6
}