#POST http://localhost:5000/roles/create HTTP/1.1
#Content-Type: application/json
#
#{
#  "value": "DEPARTMENT_HEAD"
#}

#GET http://localhost:5000/roles/all HTTP/1.1

#GET http://localhost:5000/roles/ADMIN HTTP/1.1
